### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by seagull101** [seagull101/Malignant-Metro#1]
# Storywork
- [x]  Come up with a story revolving around the metro (for multiplayer gameplay where a group of friends could join)
- [ ]  Scripts or character dialogue
- [ ]  Sketches of some areas/maps
# Assets
## 3D Models & Textures
- [ ] Need story work done first
## Dialouge & Music
- [ ] Need story work done first
# Setup Hammer
- [ ]  Build testmap.vmf
- [ ]  Import Assets
## Coding Stuff
- [ ]  Need story work done first
#Mapping
- [ ] Need story work done first
# Playthrough
## Test 1
- [ ] XX people to test and review the map on a google form
- [ ] fixup maps
## Test  2
- [ ] XX people to test and review the map on a google form
- [ ] fixup maps
## Test  3
- [ ] XX people to test and review the map on a google form
- [ ] fixup maps
# Publish
- [ ] Get steam ID
- [ ] Publish to workshop

**Comment by seagull101** [comment]
Please note, this thing will be updated as needed. If anything should be added, please comment below.

**Comment by seagull101** [comment]
hey
